version: '3.7'

services:
  booksapi:
    image: booksapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: