version: "3.9"

services:
  database:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=mongodb
    volumes:
      - mongo:/data/mongo
  app:
    build: .
    container_name: books-app
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    environment:
      - PORT=3333
      - MONGO_URL=mongodb://127.0.0.1:27017/mongodb
    links:
      - mongo
    depends_on:
      - mongo

volumes:
  mongo:
    driver: local
